id: I50FF0255
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T17:17:36+00:00'
last_modified: '2022-06-07T18:29:26.690003+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00EGS1017555
  title: གསུང་འབུམ། ཚུལ་ཁྲིམས་བློ་གྲོས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    D5B7:
      image_group_id: I1KG15468
      title: ''
      total_pages: 338
      order: 1
      base_file: D5B7.txt
    27FD:
      image_group_id: I1KG15469
      title: ''
      total_pages: 416
      order: 2
      base_file: 27FD.txt
    3F9C:
      image_group_id: I1KG15470
      title: ''
      total_pages: 422
      order: 3
      base_file: 3F9C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
